// tasks/react-basics/src/components/Header/Progress/Progress.js
import React from 'react';
import { Col, ProgressBar } from 'react-bootstrap';
import { connect } from 'react-redux';

class Progress extends React.Component {
    constructor(props) {
        super(props);
        this.items = [];
        this.tasks = [];
        this.completed = 0;
        this.percent = 100;

        this.state = {
            now: this.percent,
        };
    }

    componentWillReceiveProps(nextProps) {
        this.items.length = 0;
        this.extractItems(nextProps.store);
        this.extractTasks();
        this.countCompleted();
        this.countPercent();
    }

    extractItems(arr) {
        arr.forEach((item) => {
            this.items.push(item);
            if (item.subitems.length) this.extractItems(item.subitems);            
        });
    }

    extractTasks() {
        this.tasks.length = 0;
        this.items.forEach((item) => {
            item.tasks.forEach(state => this.tasks.push(state));
        });
    }

    countCompleted() {
        let tmp = 0;

        this.tasks.forEach((item) => {
            if (item.isDone) tmp += 1;
        });

        this.completed = tmp;
    }

    countPercent() {
        if (this.tasks.length) this.percent = (this.completed * 100) / this.tasks.length;

        this.setState({
            now: this.percent,
        });
    }

    render() {
        return (
            <Col md={12}>
                <ProgressBar now={this.state.now} />
            </Col>
        );
    }
}

export default connect(state => ({
    store: state,
}))(Progress);

// tasks/angular-basics/src/app/header/progress/progress.component.ts
import { Component, OnInit, DoCheck } from '@angular/core';
import { StoreService } from '../../store.service';

@Component({
  selector: 'app-progress',
  templateUrl: './progress.component.html',
  styleUrls: ['./progress.component.scss']
})

export class ProgressComponent implements OnInit, DoCheck {
  items: any[] = [];
  categories: any[] = [];
  tasks: any[] = [];
  completed: number = 0;
  percent: number = 100;

  constructor(private _data: StoreService) { }

  ngOnInit() {
    this._data.store.subscribe(res => this.items = res);
  }

  ngDoCheck() {
    this.categories.length = 0;
    this.extractCategories(this.items);
    this.extractTasks();
    this.countCompleted();
    this.countPercent();
  }

  extractCategories(arr) {
    arr.forEach((item) => {
        this.categories.push(item);
        if (item.subitems.length) {
          this.extractCategories(item.subitems);
        }
    });
  }

  extractTasks() {
    this.tasks.length = 0;
    this.categories.forEach((item) => {
       item.tasks.forEach(task => this.tasks.push(task));
    });
    this._data.updateAllTasks(this.tasks);
  }

  countCompleted() {
    let tmp = 0;

    this.tasks.forEach((item) => {
        if (item.isDone) {
          tmp += 1;
        }
    });

    this.completed = tmp;
  }

  countPercent() {
    if (this.tasks.length) {
      this.percent = (this.completed * 100) / this.tasks.length;
    }
  }
}

<p>
  <progressbar max="100" [value]="percent" type="info" [striped]="true"></progressbar>
</p>
